---
title: "hw6"
author: "Matthew Coulibaly"
date: "4/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
dogs = drop_na(readxl::read_xlsx('KIB - Best in Show (public).xlsx', sheet = 'Best in show full sheet')[-c(1, 2, 3),-c(2, 4,  8:10,13:31, 33:75)]%>%
  rename("Dog Breed" = "Best in show?", "Type of Dog" = "largest value", "Data Score" = "...5", "Popularity (1-173, 1=most popular)" = "160", "Popularity within breeds" = "87", "Trainability, 1 = easiest to train" = "80", "Trainability (higher score = better)" = "...12", "Size" = "...32"))
```

```{r}
dogs$`Trainability, 1 = easiest to train` = as.numeric(dogs$`Trainability, 1 = easiest to train`)
dogs$`Data Score` = as.numeric(dogs$`Data Score`)
dogs$`Popularity (1-173, 1=most popular)` = as.numeric(dogs$`Popularity (1-173, 1=most popular)`)
dogs$Intelligence = dogs$`Trainability (higher score = better)`
dogs$Intelligence[dogs$`Trainability (higher score = better)` > .5] = 'clever'
dogs$Intelligence[dogs$`Trainability (higher score = better)` < .5] = 'dumb'
dogs$numSize = dogs$Size
dogs$numSize[dogs$Size == 'small'] = 2
dogs$numSize[dogs$Size == 'medium'] = 3
dogs$numSize[dogs$Size == 'large'] = 4
ggplot(dogs, aes(x = `Data Score`, y = `Popularity (1-173, 1=most popular)`, shape = Intelligence, color = `Type of Dog`)) +
  geom_point(size = as.numeric(dogs$numSize)) +
  ylim(-20, 165) + 
  geom_vline(xintercept = 2.55) +
  geom_hline(yintercept = 67) + 
  geom_label(aes(x = 1.2, y = 165, label = "The Rightly Ignored")) +
  geom_label(aes(x = 3.65, y = 165, label = "Overlooked Treasures")) +
  geom_label(aes(x = 1.255, y = -18, label = "inexplicably Overrated")) +
  geom_label(aes(x = 3.9, y = -18, label = "Hot Dogs")) +
  xlab("Data Score (intelligence, costs, longevity, grooming, ailments, appetite)") +
  ggtitle("Best in Show: The Ultimate Data Dog") +
  geom_text(check_overlap = TRUE, label = dogs$`Dog Breed`, size = 2.5, hjust = 0, nudge_x = .05) +
  xlim(.9, 4)
```

